apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdk 35

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId "com.github.mjdev.usbfileman"
        minSdkVersion 16
        targetSdkVersion 33
        compileSdk 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        abortOnError false
    }
    namespace 'me.jahnen.libaums.core.usbfileman'

}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'

    implementation 'junit:junit:4.13.2'
    api 'androidx.appcompat:appcompat:1.6.1'
    api 'com.google.android.material:material:1.11.0'
    api project(':libaums')
    api project(':httpserver')
    api project(':storageprovider')
    api project(':javafs')
    api project(':libusbcommunication')
}
